-- ============================================================
-- CCF-006b — FICHIER NEUTRALISÉ
-- ============================================================
-- Le contenu de cette migration a été réintégré dans ccf_006
-- (20260710006000_ccf_006_documents.sql).
--
-- Ce fichier est conservé uniquement pour maintenir la continuité
-- de la séquence de timestamps de migration. Il ne contient
-- aucune instruction SQL active.
-- ============================================================
